package com.excilys.java.formation.ui;

public enum CLIActionEnum {
    DEFAULT, LIST_COMPUTERS, LIST_COMPANIES, COMPUTER_DETAILS, CREATE_COMPUTER, UPDATE_COMPUTER, DELETE_COMPUTER, COMPANY_BY_NAME, DELETE_COMPANY, EXIT;

}